"""Add missing json columns

Revision ID: 23e0ba81c3aa
Revises: 02c90e4b927c
Create Date: 2026-07-14 21:04:46.654288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e0ba81c3aa'
down_revision: Union[str, Sequence[str], None] = '02c90e4b927c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vision_prediction_history', sa.Column('feature_hash', sa.String(length=255), nullable=True))
    op.add_column('vision_prediction_history', sa.Column('ocr_output_json', sa.Text(), nullable=True))
    op.add_column('vision_prediction_history', sa.Column('vision_session_json', sa.Text(), nullable=True))
    op.add_column('vision_prediction_history', sa.Column('inference_trace_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vision_prediction_history', 'inference_trace_json')
    op.drop_column('vision_prediction_history', 'vision_session_json')
    op.drop_column('vision_prediction_history', 'ocr_output_json')
    op.drop_column('vision_prediction_history', 'feature_hash')
    # ### end Alembic commands ###
